name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Create env files
        run: |
          cat <<EOF > map_key.env
          ${{ secrets.GMAPS_API_KEY }}
          EOF
          : > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
